CREATE TABLE streamer (
    streamer_id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    email VARCHAR(255),
    password VARCHAR(255),
    nickname VARCHAR(255),
    description VARCHAR(255),
    iconUrl VARCHAR(255),
    token UUID
);

CREATE TABLE donate (
    donate_id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    streamer_id BIGINT REFERENCES streamer(streamer_id),
    nickname VARCHAR(255),
    message VARCHAR(255),
    amount INTEGER,
    region VARCHAR(255),
    date TIMESTAMP
);

CREATE TABLE fund (
    fund_id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    streamer_id BIGINT REFERENCES streamer(streamer_id),
    name VARCHAR(255),
    aim INTEGER,
    collected INTEGER,
    start_date TIMESTAMP,
    end_date TIMESTAMP
);
